### ISSUE TITLE
Using RW_* macros inside a .proc seems to always fail

### ISSUE THREAD

**Issue by devinacker** [Optiroc/libSFX#11]
```asm
.include "libSFX.i"

;-------------------------------------------------------------------------------
.segment "CODE"

.proc test
	RW_push set:a16
	RW_pull
.endproc
```

```
test.s(7): Error: Constant expression expected
../../libSFX/include/CPU.i(234): Note: Macro was defined here
test.s(7): Error: Constant expression expected
../../libSFX/include/CPU.i(238): Note: Macro was defined here
test.s(7): Error: Constant expression expected
../../libSFX/include/CPU.i(241): Note: Macro was defined here
test.s(7): Error: Constant expression expected
../../libSFX/include/CPU.i(244): Note: Macro was defined here
test.s(7): Error: Constant expression expected
../../libSFX/include/CPU.i(270): Note: Macro was defined here
../../libSFX/include/CPU.i(69): Note: Macro was defined here
"make": *** [.build/test.o] Error 1
```

Is there something non-obvious I might be doing wrong here? It seems like using any of the register size macros inside of a .proc causes problems with how those macros actually keep track of register state. I'd like to be able to tidy up my code/labels a bit but unfortunately this makes it difficult to do that without breaking any libSFX macros that use the RW macros (which is pretty much all of them...)

**Comment by devinacker** [comment]
https://gist.github.com/devinacker/976fa050cc3d2bf43e98cce95e850ec0

I haven't actually tested the result of assembling this yet (other than to make sure it _does_ assemble), but a possible solution seems to be to just keep the register widths in a scope which is then explicitly referenced in all of the RW macros

**Comment by Optiroc** [comment]
Ah, that sounds like a good solution, I should look into that! I've actually never used the `proc` scoping feature of ca65, I should probably do that at some point. :+1:

Speaking of the RW macros, last time I looked at them (after being in WLA-land for a ROM-hacking project) I started to question their value. A simpler enforced coding style seems like the better solution to me now. But even then, having macros that only emits instructions as necessary could be useful I guess.

**Comment by devinacker** [comment]
To be honest I'm mostly using the RW macros just because the (extremely useful) higher-level libSFX macros rely on them, but it's not really a bad system once you get used to it :)

After sleeping on it a bit though, there is one advantage that the current implementation has: if you `RW_assume` both register sizes at the beginning of the procedure, further macros _should_ all work, with the additional benefit that those RW values would then go out of scope and not affect any potentially unrelated code defined after the proc, which was something I tripped over a few times when first getting used to them. (I'm at work away from my SNES dev stuff right now though, so I can't verify that I actually know what I'm talking about here)

With that in mind, it might be a better idea to just give most of the RW macros (i.e. any of them that actually check the RW state variables, rather than just set them) some extra boilerplate to ensure that those variables are always defined within the current scope, rather than having every proc using state variables in the same globally-visible scope. What do you think?

**Comment by devinacker** [comment]
https://gist.github.com/devinacker/b7b3e273a2f387bf9471804b60280758

Better scoping attempt.

```asm
;-------------------------------------------------------------------------------
.segment "CODE"

RW a16i16
.out "in global scope:"
RW_print
.out ""

.proc test
	.out "in test scope:"
	RW_print
	.out ""
	
	RW_push set:a16
	
	.out "in test scope after push:"
	RW_print
	.out ""
	
	RW_pull
	
	.out "in test scope after pull:"
	RW_print
	.out ""
	
	rts
.endproc

.out "in global scope again:"
RW_print
.out ""
```

```
in global scope:
Accumulator size = 0 (16-bit)
Index size = 0 (16-bit)

in test scope:
Accumulator size = 1 (8-bit)
Index size = 0 (16-bit)

in test scope after push:
Accumulator size = 0 (16-bit)
Index size = 0 (16-bit)

in test scope after pull:
Accumulator size = 1 (8-bit)
Index size = 0 (16-bit)

in global scope again:
Accumulator size = 0 (16-bit)
Index size = 0 (16-bit)
```

edit: damn, just realized that ca65 would still be using .a8 after returning to global scope. Better keep using RW_push/RW_pull/RW_assume, I guess...

**Comment by Optiroc** [comment]
Yeah, but this ties into something I've been wanting to do for a long time actually... The basic idea is to add macros that wrap functions (replacing `.proc` and `.endproc` effectively). The bigger idea I want to accomplish is to not only fix the RW_assume/etc stuff, but also make parameter passing cleaner.

That whole thing ended up in a half-finished design of an entirely new assembly pre-processor written in Python though... But for just fixing your particular issue macros replacing proc/endproc should be a viable solution, right?

**Comment by kylophone** [comment]
Yes, it seems ca65 sometime gets confused when you try expand a macro. I've also seen it refuse to do it's job when there's a macro in between a `bra` and the local label you're trying to branch to.

The cc65 git submodule that ships with libSFX is 11 months old, maybe we should bump that and try again. If it's still an issue, we should send the cc65 guys a bug report, it seems like a pretty active community.

**Comment by devinacker** [comment]
@Optiroc I was considering something along those lines, yeah - it would be good to be able to define procs in a way that cleanly handles the RW stuff inside (and outside) of the resulting scope, without the programmer having to do a lot of stuff on their own. I could try to cook up something along those lines later tonight, maybe.

(It might even be good enough to keep the scope-initialization stuff I posted last time, but also wrap procs in RW_push/RW_pull to make sure outer scopes still assemble properly? I'd have to try it later though)

@kylophone I'm pretty sure I've noticed the same as well - IIRC I started avoiding local labels in my code just because sometimes using them around the libSFX macros caused problems for some reason. Updating cc65 would probably be a good idea.

**Comment by kylophone** [comment]
https://github.com/cc65/cc65/blob/e7cf8fb45cd32c5da449aaf85871e19ff9fd13df/src/ca65/expr.c#L1644

Just a quick look, but it seems like ca65 will throw this error when macros aren't "constant expressions". Just a hunch, but I've got a feeling that in some situations it's not smart enough to deal with macros that expand to different lengths depending on the context.

**Comment by devinacker** [comment]
I think that (as well as the thing this issue is about in the first place) may actually be some kind of scope-related bug involving whatever symbols determine how a particular macro should be expanded in the first place.

Namely, even when not using any macros at all, this can occur:

```asm
.include "libSFX.i"

;-------------------------------------------------------------------------------
.segment "CODE"

.out .sprintf("%d", SFX_RW_a_size)
.proc test
.out "entering scope"
.out .sprintf("%d", SFX_RW_a_size)
.out "leaving scope"
.endproc
.out .sprintf("%d", SFX_RW_a_size)
```

results in:

```
1
entering scope
0
leaving scope
1
test.s(9): Error: Constant expression expected
```

On the other hand, referencing `::SFX_RW_a_size` inside the proc scope successfully prints the existing value, or alternately, defining `SFX_RW_a_size` a second time inside the proc (and _not_ referencing the global scope) prints the new value inside the proc and then the original (global) value outside the proc, as expected.

This seems like a bug to me because it appears to directly contradict the current ca65 documenation:
> Symbols defined outside this local level may be accessed as long as their names are not used for new symbols inside the level.

and that despite that, it seems like referencing symbols in outer scopes simply doesn't work unless you explicitly specify the scope (even if it's the global scope).

This should probably be tested on a more recent version of ca65, but I'm pretty certain it also affects many other (non-RW-related) libSFX macros.

**edit:** This seems to be the subject of this cc65 issue: https://github.com/cc65/cc65/issues/235 in which it is considered _not_ a bug. So I guess libSFX macros just need to be more explicit about always using the global namespace (and probably, for RW stuff, making sure procs can be defined that keep RW value changes limited to that scope).

What a pain in the ass on ca65's part. I'll probably update my CPU.i changes to fix those previous scoping issues I was having and maybe try to clean up the other macros to be 'proc-safe' as well, and probably file a PR if I get it working.

**Comment by Optiroc** [comment]
I went ahead and merged your PR. As I previously admitted I'm not much of a "scoper" myself, at least when it comes to low level programming, so I don't really have any code set up that will exercise potential side effects of using various macros inside .proc-scopes. 

That cc65 will only search the global namespace if explicitly requested seems rather bonkers I must say... Sounds like yet another reason to roll a custom preprocessor and only use cc65 as a "dumb" assembler and linker. 🎢

**Comment by devinacker** [comment]
I don't tend to use scopes much in assembly code either, but I started using `.proc` for better management of local labels and stuff like that and thought it would be good for the CPU state tracking and other stuff to play nicely with those. Hopefully it should all work much better now :)

Gonna go ahead and close this, since it seems to be all good now.
