### ISSUE TITLE
LZ4 decompressor crashes with specific file

### ISSUE THREAD

**Issue by clbr** [Optiroc/libSFX#16]
I have a LZ4-compressed file that crashes the decoder in SFX_LZ4_decompress/DecodeBlock. The cpu goes haywire and the stack loops around. I have permission to send the file privately, looking up your email to do so.

**Comment by kylophone** [comment]
You didn't mention it, so I'll ask. I assume the file works cleanly with other lz4 decoders?

**Comment by Optiroc** [comment]
Hmm. I got the troublesome (compressed) file via mail, and when decompressing the stream in an isolated test project it works just fine. The decompressor function exits normally, and when viewing the memory contents it looks like well formed tile data.

Chances are there's something else going on that corrupts the stack, register sizes or some other memory.

**Comment by clbr** [comment]
Yes, it decompresses fine using the lz4 tool. Using other tile data, with the exact same code, did not crash. The NMI is off and no IRQs are set up. It's a LOROM project and the tile data is at $8000, at the start of a bank.

**Comment by Optiroc** [comment]
Hmm. The output size is fairly large. Are you sure there's enough free memory at the destination not to smash into something?

**Comment by clbr** [comment]
It's decompressed to EXRAM, and SFX_LZ4_decompress never returns.

**Comment by Optiroc** [comment]
Right. Hmm, it works fine here so *something* is not set up properly. If you can share the project files somewhere I can look into it.

**Comment by clbr** [comment]
I'm afraid that's not possible. I'll try to narrow it down.

I put a breakpoint on IsBlockDone, and it explodes after the 812th block. These were the values there:
"A:ffff X:9408 Y:4dd0 S:1ff4 D:0000 DB:80 Nvmxdizc V:223 H: 85 F:21"

**Comment by clbr** [comment]
My mistake afterall, sorry. The macro that was supposed to disable NMI did not correctly do so.

**Comment by Optiroc** [comment]
👍 

Good luck with your project!
