### ISSUE TITLE
Calling VRAM_memcpy to the same location does not work for maps?

### ISSUE THREAD

**Issue by josefcs** [Optiroc/libSFX#19]
Hello, thank you for this excellent library, it helped me kickstart my dive into snes programming!

I load a background with

        LZ4_decompress Map, EXRAM, y
        VRAM_memcpy VRAM_MAP_LOC, EXRAM, y

        LZ4_decompress Tiles, EXRAM, y
        VRAM_memcpy VRAM_TILES_LOC, EXRAM, y

        CGRAM_memcpy 0, Palette, sizeof_Palette

and after the user presses the start button, another background will be loaded with

        LZ4_decompress Scr2Map, EXRAM, y
        VRAM_memcpy VRAM_MAP_LOC, EXRAM, y

        LZ4_decompress Scr2Tile, EXRAM, y
        VRAM_memcpy VRAM_TILES_LOC, EXRAM, y

        CGRAM_memcpy 0, Scr2Pal, sizeof_Scr2Pal

Unfortunately, this other background is garbled. The palette seems to load OK, but the map seems to be broken.

I have constructed a minimal example here (copy it into a subfolder of libsfx, e.g. into the examples folder):
https://github.com/josefcs/twopage-libsfx/

Forgive me, if I am missing something obvious here, but to me this seems like a bug.
Further pointers of what is going wrong would be very apreciated.

Thank you!

**Comment by josefcs** [comment]
Sorry, it seems to be a higan error.
When emulating it with zsnes, the minimal example works.

**Comment by Optiroc** [comment]
Hi! Actually you’ve discovered two important things:

- On SNES or an accurate emulation there of you cannot perform VRAM writes during active display, only during “blanking” (vblank/hblank or forced blanking). 

- An inaccurate emulator leads to misleading conclusions and non-working code. ;)

**Comment by josefcs** [comment]
@Optiroc Thank you, didn't know about forced blanking. I updated the previously non-working minimal example and it works in both emulators now. And yes, you were right, I made the wrong conclusions based on the emulator behavior ;-)

**Comment by Optiroc** [comment]
No problem, happy to help!

VRAM management is a key component of any more advanced SNES game engine. Since you can’t use forced blanking during game play you must either make sure to never transfer more than there is time for during vertical blanking, or devise a system that queues up pending transfers over several frames if need be. 

Anyway! This proved that even ZSNES can be of help sometimes.. But never use it again! 😜
