### ISSUE TITLE
Compiler gets confused between CPU and SMP map files

### ISSUE THREAD

**Issue by Molive-0** [Optiroc/libSFX#20]
When creating a program with a map file to use for the rom and a map file to use for the SMP, the compiler gets confused and tries to use them interchangably. This causes obvious errors when the SMP doesn't have the right mapping details.

With only one map file, the CPU doesn't seem to want to steal the SMP's, but the SMP will try and use the main CPU's. This makes it impossible to create a program with a larger than normal ROM and also SMP overlays.

**Comment by Molive-0** [comment]
The easiest way to recreate this seems to be to just to try to copy one of the premade configs from the configurations folder into the example SMP-test, and then try to build it.

`ld65: Warning: Map.cfg(64): Segment 'HEADER' does not exist
ld65: Warning: Map.cfg(64): Segment 'VECTORS' does not exist
ld65: Warning: Cannot evaluate assertion in module 'SMP-Play/Play.s700', line 73
ld65: Warning: Cannot evaluate assertion in module 'SMP-Play/Play.s700', line 75
ld65: Error: Missing memory area assignment for segment 'DATA'
../../libSFX.make:131: recipe for target 'SMP-Play.bin' failed
make: *** [SMP-Play.bin] Error 1`

**Comment by Optiroc** [comment]
Hi! First, I'm sorry that I haven't been paying attention to my SNES projects for a bit too long.

Indeed the list of search paths given to the linker trips things up, so I decided to clear up the confusion by renaming the linker map `SMP-Map.cfg` for SMP maps. I don't have any "real life" use case, but the updated "SMP-Test" example seems to work as intended with a custom main configuration now.
