### ISSUE TITLE
WRAM_memset should transfer from ROM instead of VRAM

### ISSUE THREAD

**Issue by devinacker** [Optiroc/libSFX#9]
Recently, I've written a (somewhat CPU-heavy) effect that renders into a buffer and uses WRAM_memset to clear the buffer each time. Since almost all the normal vblank DMA bandwidth is used to get the buffer _into_ VRAM, I end up clearing the buffer mid-frame instead, where WRAM_memset becomes problematic on a real console.

Rather than touching VRAM, a safer option might be to just have a table of all 256 possible fill values in ROM and use that as the transfer source instead. This way, it can be safely used during active display.

**Comment by Optiroc** [comment]
True, that would be a more universally useful implementation. Wasting #$FF bytes of ROM doesn't matter much either (if you're going for "minimum footprint" like a 1KB challenge or something you wouldn't use a framework anyway). 

I'll push a fix asap.

**Comment by devinacker** [comment]
Yeah, don't worry, I'm not size coding this time :)

**Comment by Optiroc** [comment]
I committed a fix using your suggested approach. I didn't do any extensive testing (since I'm actually out camping (!)), but I think it's good to go.

**Comment by kylophone** [comment]
@Optiroc Haha, I really enjoy the fact you pushed some SNES code from the campsite. 😎

**Comment by devinacker** [comment]
Seems to work great now, thanks! Hope it didn't take too much time away from camping :)
